### ISSUE TITLE
Illegal move!

### ISSUE THREAD

**Issue by toni-chess** [Mergener/illumina#49]
Hi there!
Illumina 1.0 r189 often makes illegal moves.

Hardware: Intel(R) Core(TM) i5-4570 3.20GHz 8GB RAM
OS: Windows 10 x64 Pro
GUI: Arena 3.5.1
TimeControl : 09s+0.1s

Illumina Configuration:

[Illumina 1.0 r189 x64(AVX2)]
Hash=16
Threads=1
Contempt=0
MultiPV=1

**Comment by Mergener** [comment]
Hi @toni-chess! There's a known issue that I'll fix ASAP where Illumina tries to block checks by trying to promote a pawn with a double push. If that's the type of illegal move you've encountered, I'm already working on it and will push a fix soon. Anyway, thanks for the heads up!

**Comment by Mergener** [comment]
Fixed in PR #50

**Comment by toni-chess** [comment]
Hi Mergener!
I sarted  testing new version of your program(Illumina 1.0 x64(BMI2) and unfortunately the problem remain.
I don't know what illegal move is but Arena report it. If you test Illumina under Arena you will see.
hope you understand my poor english!
best wisshes!

**Comment by toni-chess** [comment]
Here is the link to [Download Arena GUI 3.5.1](http://www.playwitharena.de/downloads/arena_3.5.1.zip)
If the link not wrk, just copy and past it on link bar and then press enter. Normally it will be downladed in this way. 
I'm Brazilian fan but don't like Neymar :)

**Comment by Mergener** [comment]
Hi @toni-chess! Basically, Illumina is performing pretty badly in non-increment time controls, and when she gets really low on time illegal moves are being played. I'm working on both improving the time control code and preventing illegal moves from being outputted in any circumstances.

And I don't really like Neymar either

**Comment by Mergener** [comment]
Fixed in #58.
